# Common-subset HCL: this file (and every other file in this module) must run unchanged under
# both OpenTofu and Terraform. See infra/aws-serverless/README.md for why:
# OpenTofu is the primary target (state encryption / early variable evaluation are OpenTofu-only
# and must never be used here), Terraform support is a first-class compatibility promise, not an
# afterthought.
#
# `>= 1.9.0` (PR #80 review, was wrongly `>= 1.8.0`): `create_api`'s validation block
# (variables.tf) references `var.dev_endpoint_url` from a different variable's condition —
# cross-object validation, which both toolchains only shipped starting in their own 1.9.0
# (verified 2026-07-26: HashiCorp's "Terraform 1.9 enhances input variable validations" and
# OpenTofu's #1336/1.9.0 milestone both land the same feature at the same version number). On
# 1.8.x this is a hard parse error — "Invalid reference in variable validation" — so the first
# adopter honouring the previously-declared `>= 1.8.0` floor could not even `init`. CI never
# caught this because it pins 1.12.5, well above the true floor.
terraform {
  required_version = ">= 1.9.0"

  required_providers {
    aws = {
      # Fully qualified to `registry.opentofu.org` (PR #80 review, finding #10) rather than the
      # bare "hashicorp/aws" each tool would otherwise expand against its OWN default registry
      # host: with the short form, `tofu init` writes a lock file entry keyed
      # `registry.opentofu.org/hashicorp/aws` and a subsequent plain `terraform init` doesn't
      # merge alongside it — it deletes that entry as "no longer required" and adds its own
      # `registry.terraform.io/...` one instead (confirmed by hand: 2026-07-26), so
      # `terraform init -lockfile=readonly` (the mode any read-only/CI init should use) fails
      # outright the moment the committed lock file was last regenerated by `tofu init`, which
      # every lock file in this module currently is. Pinning the explicit host makes both tools
      # resolve, install from, and lock the identical fully-qualified address, so ONE committed
      # `.terraform.lock.hcl` satisfies `-lockfile=readonly` under either toolchain (verified by
      # hand against this exact module 2026-07-26). registry.opentofu.org mirrors the identical
      # upstream provider `terraform.io` does (this file's prior comment already said so), and
      # Terraform can install from any host that speaks the standard registry protocol — which
      # is all this is.
      source  = "registry.opentofu.org/hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
